version: 2.1
jobs:
  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "execute docker build"
          command: "docker build -t test ."
workflows:
  build-docker-workflow:
    jobs:
      - build-docker
